spring:
  application:
    name: eureka-server

server:
  port: 9001

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    metadataMap:
      zone: beijing
  client:
    region: china
    preferSameZoneEureka: true
    registerWithEureka: true
    fetchRegistry: true
    availabilityZones:
      china: beijing,shanghai
    serviceUrl:
      beijing: http://127.0.0.1:9001/eureka/
      shanghai: http://127.0.0.1:9002/eureka/